ci:
  skip: [pytest]

# default_language_version:
#   python: python3.13

repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.6.3
    hooks:
      - id: uv-lock

  # general checks (see here: https://pre-commit.com/hooks.html)
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: end-of-file-fixer
      - id: trailing-whitespace

  # prettier - formatting JS, CSS, JSON, Markdown, ...
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        exclude: ^uv.lock
  # uv test
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: uv run ruff format
        language: system
        types: [python]
        pass_filenames: false
      - id: mypy
        name: mypy
        entry: uv run mypy --config-file=pyproject.toml classify
        language: system
        types: [python]
        pass_filenames: false
      - id: pytest
        name: pytest
        entry: uv run pytest tests -vv
        language: system
        types: [python]
        pass_filenames: false
