plugins:
  [
    "@semantic-release/commit-analyzer",
    "@semantic-release/release-notes-generator",
    "@semantic-release/changelog",
    "@covage/semantic-release-poetry-plugin",
    [
      "@semantic-release/git",
      {
        "assets": ["*.md", "pyproject.toml"],
        "message": "chore(semantic-release): release ${nextRelease.version}",
      },
    ],
  ]
branches:
  - "main"
