name: release
on:
  push:
    branches:
      - main

permissions:
  contents: read # for checkout

jobs:
  tests:
    uses: ./.github/workflows/tests.yml

  release:
    name: Release
    needs: [tests]
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        with:
          extra_plugins: |
            @semantic-release/git@10
